services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
