services:
  api-dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres

  api-repl:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npx nest start --entryFile repl
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - /data/postgres/project-template:/data/postgres
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres:
