name: Run backend tests

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Run Docker image
        working-directory: ./apps/api
        run: docker-compose -f tests.docker-compose.yaml run -d --name=tests tests sh

      - name: Run Prisma migration
        run: docker exec tests npm run prisma:migrate:deploy

      - name: Run unit tests
        run: docker exec tests npx jest

      - name: Run e2e tests
        run: docker exec tests npx jest --config ./tests/jest-e2e.json
      
      - name: Quit Docker containers
        run: docker-compose -f tests.docker-compose.yaml down