name: Run backend tests

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/api/**'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./apps/api
          builder: ${{ steps.buildx.outputs.name }}
          target: development
          push: false
          load: true
          tags: template:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run Docker image
        working-directory: ./apps/api
        # run: docker-compose -f docker-compose.tests.yaml run -d --name=tests tests-base sh
        run: docker run -d --name=tests template:latest sh

      - name: Run Prisma migration
        run: docker exec tests npm run prisma:migrate:deploy

      - name: Run unit tests
        run: docker exec tests npx jest

      - name: Run e2e tests
        run: docker exec tests npx jest --config ./tests/jest-e2e.json
      
      - name: Quit Docker containers
        working-directory: ./apps/api
        run: docker-compose -f docker-compose.tests.yaml down